version: '3.7'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  prometheus:
    image: bitnami/prometheus:latest
    volumes:
      - ./prometheus/:/var/lib
      - prometheus_data:/prometheus-data
    command:
      - '--config.file=/home/prometheus_files/spring-boot-prometheus.yml'
      - '--storage.tsdb.path=/prometheus-data'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9002:9090
    restart: always