#docker run --name=prometheus -p 9002:9090 -v /home/prometheus_files/spring-boot-prometheus.yml:/etc/prometheus/prometheus.yml -d bitnami/prometheus:latest

global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'any_name_here_apis'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'rest-job-name-or-microservice'
    metrics_path: 'rest-job-name-or-microservice/actuator/prometheus'
    basic_auth:
      username: 'user-here'
      password: 'password-here'
    static_configs:
    - targets: ['192.168.1.1']
  
  - job_name: 'prometheus'
    metrics_path: '/metrics'
    static_configs:
    - targets: ['localhost:9090']
